"""empty message

Revision ID: 02f55f5f22cc
Revises: d5c0a8e3ab0b
Create Date: 2026-03-23 17:49:23.035539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f55f5f22cc'
down_revision = 'd5c0a8e3ab0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=120), nullable=False),
    sa.Column('reciever_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'reciever_id', 'sender_id'),
    sa.UniqueConstraint('message')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dm')
    # ### end Alembic commands ###
