"""empty message

Revision ID: 64b9d2138192
Revises: a5cffa318ac2
Create Date: 2026-03-20 20:25:08.202389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b9d2138192'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('photo', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['photo'])
        batch_op.create_unique_constraint(None, ['description'])
        batch_op.create_unique_constraint(None, ['user'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('description')
        batch_op.drop_column('photo')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
