"""empty message

Revision ID: 696178125b9b
Revises: 15aecda5260c
Create Date: 2026-03-25 20:22:49.323524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696178125b9b'
down_revision = '15aecda5260c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_user_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('comment_user_id_key', ['user_id'])

    # ### end Alembic commands ###
