"""empty message

Revision ID: 7d7528f7bdef
Revises: 02f55f5f22cc
Create Date: 2026-03-23 17:51:04.055964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7528f7bdef'
down_revision = '02f55f5f22cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seguido_id', sa.Integer(), nullable=False),
    sa.Column('seguidores_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'seguido_id', 'seguidores_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
